[package]
name = "proposal"
version = "0.1.0"
authors = ["Kunta Labs"]
edition = "2018"

[dependencies]
db = { path = "../db" }
block = { path = "../block" }
timestamp = { path = "../timestamp" }
hash = { path = "../hash" }
executor = { path = "../executor" }
rustc-serialize = "0.3"
json = "*"
