[package]
name = "src"
version = "0.1.0"
authors = ["Kunta Labs"]
edition = "2018"

[dependencies]

[[bin]]
name = "src"
path = "main.rs"
#may not need, only cargo test throws this error for node import
node = { path = "../node"}
