[package]
name = "executor"
version = "0.1.0"
authors = ["Kunta Labs"]
edition = "2018"

[dependencies]
json = "*"
macros = { path = "../macros" }
timestamp = { path = "../timestamp" }
signature = { path = "../signature" }
encode = { path = "../encode" }
