[package]
name = "core"
version = "0.1.0"
authors = ["Kunta Labs"]
edition = "2018"

[dependencies]
node = { path = "node" }
proposal = { path = "proposal" }
block = { path = "block" }
timestamp = { path = "timestamp" }
json = "*"
hash = { path = "hash" }
network = { path = "network" }
