[package]
name = "network"
version = "0.1.0"
authors = ["Kunta Labs"]
edition = "2018"

[dependencies]
http = "0.1"
reqwest = "0.9.22"
proposal = { path = "../proposal" }
encode = { path = "../encode" }
transaction = { path = "../transaction" }
block = { path = "../block" }
url = "2.1.0"
