[package]
name = "node"
version = "0.1.0"
authors = ["Kunta Labs"]
edition = "2018"

[dependencies]
network = { path = "../network" }
transaction = { path = "../transaction" }
db = { path = "../db"}
proposal = { path = "../proposal"}
block = { path = "../block"}
json = "*"
