[package]
name = "transaction"
version = "0.1.0"
authors = ["Kunta Labs"]
edition = "2018"

[dependencies]
json = "*"
db = { path = "../db" }
timestamp = { path = "../timestamp" }
hash = { path = "../hash" }
encode = { path = "../encode" }
